### PR TITLE
Relaying a NIL position to FILE-POSITION isn't allowed.

### PR DESCRIPTION
**Pull request by phmarek**

### CODE REVIEW

**Comment by j3pic** [comment]
The `:include`: logic is great. It would be difficult to get the EOF handling to work correctly for *all* types. Because of the way it's written, your `handler-bind` function would have to know which field was being read, and how many bytes are expected. If you know that information, you can already invoke the `lisp-binary::enter-value` restart with a valid value. It would be better to define a restart within `read-bytes`, where at least the number of bytes is known. `read-bytes` could then return the correct number of zeroes and hope that the upstream code can do something with that.

Additional restarts could be added to readers that expect specific values, such as magic numbers, enums, and `(eval (case value ...)` types, to allow them to evaluate to _something_ (but that something would have to match the declared `:type` in the generated `defstruct` form).

**Comment by phmarek** [comment]
Ah sorry, I forgot that Github will change PRs when I move my branch around.

Of course, all the later commits don't belong here in this PR -- but if you find something useful, just cherry-pick!

**Comment by j3pic** [comment]
I came up with an entirely different solution to the partial-read problem: We already had the `ENTER-VALUE` restart available whenever an error happened when reading a field. I renamed it to `USE-VALUE` because that name is used by SBCL and other CL implementations. And I added a `:UNTYPED-STRUCT` option that causes the generated `DEFSTRUCT` form to be untyped. This allows you to do a partial read like this:

```common-lisp
(defbinary example (:untyped-struct t)
  (a 0 :type (unsigned-byte 24))
  (b 0 :type (unsigned-byte 4))
  (c 0 :type (unsigned-byte 20)))


(handler-bind
  ((end-of-file (lambda (cond)
                  (invoke-restart 'use-value nil))))
  (with-open-binary-file (in #P"/tmp/foobar.bin")
     (read-binary 'example in)))
```

Then your struct will have `nil` starting at the point where the `end-of-file` error was first reached.

**Comment by phmarek** [comment]
Ah, that sounds nice!

And if I can't spare the space (because a few million structures with a few `(unsigned-byte 8)` slots are smaller than when they may store `NIL`) I can still `:use-value 0` instead.

BTW: shouldn't that be `:use-value`, the keyword?

**Comment by j3pic** [comment]
It turns out that the `use-value` (which is `cl:use-value` *not* `:use-value`) does not appear where you'd need it for this use-case. The `read-bytes` function has a `cl:continue` restart on EOF. I'm going to make sure that restart is available for all read functions, including the bit-stream ones.

In case the struct has a magic number, that has a `continue` restart as well, but the condition will be of type `lisp-binary:bad-magic-value`.

This unit test passed:

```common-lisp
(unit-test 'untyped-struct-test
    (flexi-streams:with-input-from-sequence (in '(0 0 0))
      (handler-bind
	  (((or end-of-file bad-magic-value)
	    (lambda (cond)
	      (declare (ignore cond))
	      (invoke-restart 'continue))))
	(let ((obj (read-binary 'example in)))
	  (assert= (slot-value obj 'a) 0)
	  (assert= (slot-value obj 'b) 0)
	  (assert= (slot-value obj 'c) 0)))))
```

**Comment by j3pic** [comment]
One thing to be aware of: Since in the case of EOF you can't guarantee that null bytes will satisfy the requirements of the struct's declared types, the `:untyped-struct` option causes the resulting struct to be untyped, which means all the values will be tagged. This might increase the size of the struct relative to its typed variant.

**Pull request merged**
